# Generated by Django 3.1.7 on 2021-02-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHeads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=50)),
                ('opening_balance', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLogDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountname')),
                ('journal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journallog')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_type_name', models.CharField(max_length=50)),
                ('acc_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountheads')),
            ],
        ),
        migrations.AddField(
            model_name='accountname',
            name='type_of_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounttype'),
        ),
    ]
