# Generated by Django 3.1.7 on 2021-02-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journallog',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
